# ============================================================================
# Random Policy 配置（Baseline）
# ============================================================================

algorithm:
  name: "RANDOM"
  class: "custom"                    # 自定义实现

# Random策略没有超参数
hyperparameters: {}

# 用于统一接口
device: "cpu"
seed: null