action_space:
  dtype: float32
  high: 1.0
  low: -1.0
  shape:
  - 2
  type: Box
environment:
  evader_speed: 0.01
  local_ratio: 0.5
  max_cycles: 500
  n_evaders: 90
  n_obstacles: 2
  n_poisons: 10
  n_predators: 5
  n_preys: 10
  name: waterworld_v4
  obstacle_coord:
  - - 0.2
    - 0.2
  - - 0.8
    - 0.2
  poison_speed: 0.01
  predator_speed: 0.06
  prey_speed: 0.001
  render_mode: null
  sensor_range: 0.8
  static_food: true
  static_poison: true
  thrust_penalty: 0.0
observation_space:
  dtype: float32
  shape:
  - 212
  type: Box
